/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_fenetre_reserve_excursion (void);
GtkWidget* create_fenetre_panier_excursion (void);
GtkWidget* create_fenetre_client_excursion (void);
