/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_interface1 (void);
GtkWidget* create_interface2 (void);
GtkWidget* create_interface3 (void);
GtkWidget* create_interface4 (void);
GtkWidget* create_interface5 (void);
GtkWidget* create_interface6 (void);
GtkWidget* create_interface7 (void);
GtkWidget* create_interface8 (void);
GtkWidget* create_interface9 (void);
GtkWidget* create_interface10 (void);
GtkWidget* create_interface11 (void);
GtkWidget* create_interface12 (void);
GtkWidget* create_interface13 (void);
