/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_interface1 (void);
GtkWidget* create_interface2 (void);
GtkWidget* create_interface3 (void);
GtkWidget* create_interface4 (void);
GtkWidget* create_interface5 (void);
GtkWidget* create_interface6 (void);
GtkWidget* create_interface7 (void);
GtkWidget* create_interface8 (void);
GtkWidget* create_interface9 (void);
GtkWidget* create_interface10 (void);
GtkWidget* create_interface11 (void);
GtkWidget* create_interface12 (void);
GtkWidget* create_interface13 (void);
GtkWidget* create_interface14 (void);
GtkWidget* create_interface15 (void);
GtkWidget* create_interface16 (void);
GtkWidget* create_interface17 (void);
GtkWidget* create_interface18 (void);
GtkWidget* create_interface19 (void);
GtkWidget* create_interface20 (void);
GtkWidget* create_interface21 (void);
GtkWidget* create_interface22 (void);
GtkWidget* create_interface23 (void);
GtkWidget* create_interface24 (void);
GtkWidget* create_interface25 (void);
GtkWidget* create_interface26 (void);
GtkWidget* create_interface27 (void);
GtkWidget* create_interface28 (void);
GtkWidget* create_interface29 (void);
GtkWidget* create_interface30 (void);
GtkWidget* create_interface31 (void);
GtkWidget* create_interface32 (void);
GtkWidget* create_interface33 (void);
GtkWidget* create_interface34 (void);
