/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_interface_p (void);
GtkWidget* create_interface_inscription (void);
GtkWidget* create_interface_client (void);
GtkWidget* create_interface_admin (void);
GtkWidget* create_interface_prop (void);
GtkWidget* create_interface_agent (void);
