/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_interface_p (void)
{
  GtkWidget *interface_p;
  GtkWidget *fixed1;
  GtkWidget *entryLogin;
  GtkWidget *entryMdp;
  GtkWidget *labelMdp;
  GtkWidget *labelNom;
  GtkWidget *label1;
  GtkWidget *buttonLogin;
  GtkWidget *buttonnc;
  GtkWidget *buttonCc;

  interface_p = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (interface_p, 500, 400);
  gtk_window_set_title (GTK_WINDOW (interface_p), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (interface_p), fixed1);

  entryLogin = gtk_entry_new ();
  gtk_widget_show (entryLogin);
  gtk_fixed_put (GTK_FIXED (fixed1), entryLogin, 184, 56);
  gtk_widget_set_size_request (entryLogin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryLogin), 8226);

  entryMdp = gtk_entry_new ();
  gtk_widget_show (entryMdp);
  gtk_fixed_put (GTK_FIXED (fixed1), entryMdp, 184, 120);
  gtk_widget_set_size_request (entryMdp, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entryMdp), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryMdp), 8226);

  labelMdp = gtk_label_new (_("Password"));
  gtk_widget_show (labelMdp);
  gtk_fixed_put (GTK_FIXED (fixed1), labelMdp, 48, 120);
  gtk_widget_set_size_request (labelMdp, 72, 24);

  labelNom = gtk_label_new (_("Login"));
  gtk_widget_show (labelNom);
  gtk_fixed_put (GTK_FIXED (fixed1), labelNom, 56, 56);
  gtk_widget_set_size_request (labelNom, 56, 24);

  label1 = gtk_label_new (_("nouvel utilisateur ?"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 8, 272);
  gtk_widget_set_size_request (label1, 216, 40);

  buttonLogin = gtk_button_new_with_mnemonic (_("login"));
  gtk_widget_show (buttonLogin);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonLogin, 240, 192);
  gtk_widget_set_size_request (buttonLogin, 66, 29);

  buttonnc = gtk_button_new_with_mnemonic (_("Creer votre compte"));
  gtk_widget_show (buttonnc);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonnc, 48, 320);
  gtk_widget_set_size_request (buttonnc, 144, 40);

  buttonCc = gtk_button_new_with_mnemonic (_("Consulter nos catalogues"));
  gtk_widget_show (buttonCc);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonCc, 296, 328);
  gtk_widget_set_size_request (buttonCc, 200, 32);

  g_signal_connect ((gpointer) buttonLogin, "clicked",
                    G_CALLBACK (on_buttonLogin_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (interface_p, interface_p, "interface_p");
  GLADE_HOOKUP_OBJECT (interface_p, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (interface_p, entryLogin, "entryLogin");
  GLADE_HOOKUP_OBJECT (interface_p, entryMdp, "entryMdp");
  GLADE_HOOKUP_OBJECT (interface_p, labelMdp, "labelMdp");
  GLADE_HOOKUP_OBJECT (interface_p, labelNom, "labelNom");
  GLADE_HOOKUP_OBJECT (interface_p, label1, "label1");
  GLADE_HOOKUP_OBJECT (interface_p, buttonLogin, "buttonLogin");
  GLADE_HOOKUP_OBJECT (interface_p, buttonnc, "buttonnc");
  GLADE_HOOKUP_OBJECT (interface_p, buttonCc, "buttonCc");

  return interface_p;
}

GtkWidget*
create_interface_inscription (void)
{
  GtkWidget *interface_inscription;
  GtkWidget *fixed2;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label7;
  GtkWidget *label6;
  GtkWidget *buttonCc2;

  interface_inscription = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (interface_inscription, 450, 400);
  gtk_window_set_title (GTK_WINDOW (interface_inscription), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (interface_inscription), fixed2);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1, 184, 48);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2, 184, 96);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed2), entry3, 184, 144);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4, 184, 192);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed2), entry5, 184, 240);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed2), entry6, 184, 288);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  label2 = gtk_label_new (_("Nom Complet"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed2), label2, 56, 48);
  gtk_widget_set_size_request (label2, 120, 24);

  label3 = gtk_label_new (_("Login"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed2), label3, 64, 96);
  gtk_widget_set_size_request (label3, 88, 24);

  label4 = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed2), label4, 48, 144);
  gtk_widget_set_size_request (label4, 120, 24);

  label5 = gtk_label_new (_("Adress mail"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 40, 192);
  gtk_widget_set_size_request (label5, 128, 32);

  label7 = gtk_label_new (_("num t\303\251l\303\251phone"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 40, 280);
  gtk_widget_set_size_request (label7, 128, 40);

  label6 = gtk_label_new (_("num CIN"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 48, 240);
  gtk_widget_set_size_request (label6, 112, 32);

  buttonCc2 = gtk_button_new_with_mnemonic (_("Creer"));
  gtk_widget_show (buttonCc2);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonCc2, 376, 352);
  gtk_widget_set_size_request (buttonCc2, 66, 29);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (interface_inscription, interface_inscription, "interface_inscription");
  GLADE_HOOKUP_OBJECT (interface_inscription, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (interface_inscription, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (interface_inscription, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (interface_inscription, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (interface_inscription, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (interface_inscription, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (interface_inscription, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (interface_inscription, label2, "label2");
  GLADE_HOOKUP_OBJECT (interface_inscription, label3, "label3");
  GLADE_HOOKUP_OBJECT (interface_inscription, label4, "label4");
  GLADE_HOOKUP_OBJECT (interface_inscription, label5, "label5");
  GLADE_HOOKUP_OBJECT (interface_inscription, label7, "label7");
  GLADE_HOOKUP_OBJECT (interface_inscription, label6, "label6");
  GLADE_HOOKUP_OBJECT (interface_inscription, buttonCc2, "buttonCc2");

  return interface_inscription;
}

GtkWidget*
create_interface_client (void)
{
  GtkWidget *interface_client;
  GtkWidget *fixed3;
  GtkWidget *notebook1;
  GtkWidget *fixed4;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label15;
  GtkWidget *label14;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *buttonMc;
  GtkWidget *buttonDes;
  GtkWidget *buttonDec;
  GtkWidget *label13;
  GtkWidget *label19;
  GtkWidget *label18;
  GtkWidget *label8;
  GtkWidget *fixed5;
  GtkWidget *treeview1;
  GtkWidget *comboboxtype;
  GtkWidget *comboboxchoix;
  GtkWidget *buttonAr;
  GtkWidget *label9;
  GtkWidget *fixed6;
  GtkWidget *treeview2;
  GtkWidget *combocr;
  GtkWidget *buttonmr;
  GtkWidget *buttonsr;
  GtkWidget *label10;
  GtkWidget *fixed7;
  GtkWidget *label11;
  GtkWidget *fixed8;
  GtkWidget *label12;

  interface_client = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (interface_client, 700, 400);
  gtk_window_set_title (GTK_WINDOW (interface_client), _("window3"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (interface_client), fixed3);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed3), notebook1, 24, 16);
  gtk_widget_set_size_request (notebook1, 672, 376);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  label16 = gtk_label_new (_("Adresse mail"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 24, 128);
  gtk_widget_set_size_request (label16, 112, 40);

  label17 = gtk_label_new (_("Login"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed4), label17, 56, 96);
  gtk_widget_set_size_request (label17, 48, 24);

  label15 = gtk_label_new (_("Cin"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed4), label15, 40, 168);
  gtk_widget_set_size_request (label15, 80, 32);

  label14 = gtk_label_new (_("Num de t\303\251l\303\251phone"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed4), label14, 24, 208);
  gtk_widget_set_size_request (label14, 136, 32);

  label20 = gtk_label_new ("");
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 192, 136);
  gtk_widget_set_size_request (label20, 192, 24);

  label21 = gtk_label_new ("");
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed4), label21, 192, 168);
  gtk_widget_set_size_request (label21, 192, 24);

  label22 = gtk_label_new ("");
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed4), label22, 192, 208);
  gtk_widget_set_size_request (label22, 192, 24);

  buttonMc = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (buttonMc);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonMc, 496, 112);
  gtk_widget_set_size_request (buttonMc, 104, 40);

  buttonDes = gtk_button_new_with_mnemonic (_("Se D\303\251sabonner"));
  gtk_widget_show (buttonDes);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonDes, 472, 232);
  gtk_widget_set_size_request (buttonDes, 128, 48);

  buttonDec = gtk_button_new_with_mnemonic (_("Se D\303\251connecter"));
  gtk_widget_show (buttonDec);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonDec, 472, 288);
  gtk_widget_set_size_request (buttonDec, 130, 37);

  label13 = gtk_label_new (_("Nom Complet"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed4), label13, 24, 48);
  gtk_widget_set_size_request (label13, 112, 32);

  label19 = gtk_label_new ("");
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 192, 96);
  gtk_widget_set_size_request (label19, 192, 24);

  label18 = gtk_label_new ("");
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 192, 48);
  gtk_widget_set_size_request (label18, 192, 24);

  label8 = gtk_label_new (_("Compte"));
  gtk_widget_show (label8);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label8);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview1, 8, 16);
  gtk_widget_set_size_request (treeview1, 648, 232);

  comboboxtype = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxtype);
  gtk_fixed_put (GTK_FIXED (fixed5), comboboxtype, 120, 280);
  gtk_widget_set_size_request (comboboxtype, 160, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxtype), _("ff"));

  comboboxchoix = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxchoix);
  gtk_fixed_put (GTK_FIXED (fixed5), comboboxchoix, 304, 280);
  gtk_widget_set_size_request (comboboxchoix, 160, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxchoix), _("ff"));

  buttonAr = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (buttonAr);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonAr, 520, 288);
  gtk_widget_set_size_request (buttonAr, 80, 32);

  label9 = gtk_label_new (_("Catalogues"));
  gtk_widget_show (label9);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label9);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview2, 8, 16);
  gtk_widget_set_size_request (treeview2, 640, 248);

  combocr = gtk_combo_box_new_text ();
  gtk_widget_show (combocr);
  gtk_fixed_put (GTK_FIXED (fixed6), combocr, 128, 296);
  gtk_widget_set_size_request (combocr, 216, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combocr), _("ff"));

  buttonmr = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (buttonmr);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonmr, 424, 304);
  gtk_widget_set_size_request (buttonmr, 80, 32);

  buttonsr = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (buttonsr);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonsr, 544, 304);
  gtk_widget_set_size_request (buttonsr, 96, 32);

  label10 = gtk_label_new (_("R\303\251servations"));
  gtk_widget_show (label10);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label10);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);

  label11 = gtk_label_new (_("Factures"));
  gtk_widget_show (label11);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label11);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed8);

  label12 = gtk_label_new (_("Reclamations"));
  gtk_widget_show (label12);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label12);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (interface_client, interface_client, "interface_client");
  GLADE_HOOKUP_OBJECT (interface_client, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (interface_client, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (interface_client, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (interface_client, label16, "label16");
  GLADE_HOOKUP_OBJECT (interface_client, label17, "label17");
  GLADE_HOOKUP_OBJECT (interface_client, label15, "label15");
  GLADE_HOOKUP_OBJECT (interface_client, label14, "label14");
  GLADE_HOOKUP_OBJECT (interface_client, label20, "label20");
  GLADE_HOOKUP_OBJECT (interface_client, label21, "label21");
  GLADE_HOOKUP_OBJECT (interface_client, label22, "label22");
  GLADE_HOOKUP_OBJECT (interface_client, buttonMc, "buttonMc");
  GLADE_HOOKUP_OBJECT (interface_client, buttonDes, "buttonDes");
  GLADE_HOOKUP_OBJECT (interface_client, buttonDec, "buttonDec");
  GLADE_HOOKUP_OBJECT (interface_client, label13, "label13");
  GLADE_HOOKUP_OBJECT (interface_client, label19, "label19");
  GLADE_HOOKUP_OBJECT (interface_client, label18, "label18");
  GLADE_HOOKUP_OBJECT (interface_client, label8, "label8");
  GLADE_HOOKUP_OBJECT (interface_client, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (interface_client, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (interface_client, comboboxtype, "comboboxtype");
  GLADE_HOOKUP_OBJECT (interface_client, comboboxchoix, "comboboxchoix");
  GLADE_HOOKUP_OBJECT (interface_client, buttonAr, "buttonAr");
  GLADE_HOOKUP_OBJECT (interface_client, label9, "label9");
  GLADE_HOOKUP_OBJECT (interface_client, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (interface_client, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (interface_client, combocr, "combocr");
  GLADE_HOOKUP_OBJECT (interface_client, buttonmr, "buttonmr");
  GLADE_HOOKUP_OBJECT (interface_client, buttonsr, "buttonsr");
  GLADE_HOOKUP_OBJECT (interface_client, label10, "label10");
  GLADE_HOOKUP_OBJECT (interface_client, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (interface_client, label11, "label11");
  GLADE_HOOKUP_OBJECT (interface_client, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (interface_client, label12, "label12");

  return interface_client;
}

GtkWidget*
create_interface_admin (void)
{
  GtkWidget *interface_admin;
  GtkWidget *fixed9;
  GtkWidget *notebook2;
  GtkWidget *fixed10;
  GtkWidget *fixed12;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *buttonMca;
  GtkWidget *buttonDeca;
  GtkWidget *label29;
  GtkWidget *label;
  GtkWidget *label23;
  GtkWidget *fixed11;
  GtkWidget *treeview3;
  GtkWidget *buttonaa;
  GtkWidget *buttonma;
  GtkWidget *buttonsa;
  GtkWidget *label24;

  interface_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (interface_admin), _("window1"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (interface_admin), fixed9);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_fixed_put (GTK_FIXED (fixed9), notebook2, 16, 24);
  gtk_widget_set_size_request (notebook2, 680, 464);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed10);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_fixed_put (GTK_FIXED (fixed10), fixed12, 0, 0);
  gtk_widget_set_size_request (fixed12, 0, 0);

  label25 = gtk_label_new (_("Adresse mail"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed12), label25, 24, 128);
  gtk_widget_set_size_request (label25, 112, 40);

  label26 = gtk_label_new (_("Login"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed12), label26, 56, 96);
  gtk_widget_set_size_request (label26, 48, 24);

  label27 = gtk_label_new (_("Cin"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed12), label27, 40, 168);
  gtk_widget_set_size_request (label27, 80, 32);

  label28 = gtk_label_new (_("Num de t\303\251l\303\251phone"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed12), label28, 24, 208);
  gtk_widget_set_size_request (label28, 136, 32);

  label30 = gtk_label_new ("");
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed12), label30, 192, 136);
  gtk_widget_set_size_request (label30, 192, 24);

  label31 = gtk_label_new ("");
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed12), label31, 192, 168);
  gtk_widget_set_size_request (label31, 192, 24);

  label32 = gtk_label_new ("");
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed12), label32, 192, 208);
  gtk_widget_set_size_request (label32, 192, 24);

  label33 = gtk_label_new (_("Nom Complet"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed12), label33, 24, 48);
  gtk_widget_set_size_request (label33, 112, 32);

  buttonMca = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (buttonMca);
  gtk_fixed_put (GTK_FIXED (fixed12), buttonMca, 496, 112);
  gtk_widget_set_size_request (buttonMca, 104, 40);

  buttonDeca = gtk_button_new_with_mnemonic (_("Se D\303\251connecter"));
  gtk_widget_show (buttonDeca);
  gtk_fixed_put (GTK_FIXED (fixed12), buttonDeca, 472, 288);
  gtk_widget_set_size_request (buttonDeca, 130, 37);

  label29 = gtk_label_new ("");
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed12), label29, 192, 96);
  gtk_widget_set_size_request (label29, 192, 24);

  label = gtk_label_new ("");
  gtk_widget_show (label);
  gtk_fixed_put (GTK_FIXED (fixed12), label, 192, 48);
  gtk_widget_set_size_request (label, 192, 24);

  label23 = gtk_label_new (_("Compte"));
  gtk_widget_show (label23);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label23);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed11);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed11), treeview3, 16, 24);
  gtk_widget_set_size_request (treeview3, 648, 256);

  buttonaa = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (buttonaa);
  gtk_fixed_put (GTK_FIXED (fixed11), buttonaa, 88, 336);
  gtk_widget_set_size_request (buttonaa, 96, 37);

  buttonma = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (buttonma);
  gtk_fixed_put (GTK_FIXED (fixed11), buttonma, 248, 336);
  gtk_widget_set_size_request (buttonma, 96, 37);

  buttonsa = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (buttonsa);
  gtk_fixed_put (GTK_FIXED (fixed11), buttonsa, 400, 336);
  gtk_widget_set_size_request (buttonsa, 96, 37);

  label24 = gtk_label_new (_("Listes Agents"));
  gtk_widget_show (label24);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label24);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (interface_admin, interface_admin, "interface_admin");
  GLADE_HOOKUP_OBJECT (interface_admin, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (interface_admin, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (interface_admin, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (interface_admin, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (interface_admin, label25, "label25");
  GLADE_HOOKUP_OBJECT (interface_admin, label26, "label26");
  GLADE_HOOKUP_OBJECT (interface_admin, label27, "label27");
  GLADE_HOOKUP_OBJECT (interface_admin, label28, "label28");
  GLADE_HOOKUP_OBJECT (interface_admin, label30, "label30");
  GLADE_HOOKUP_OBJECT (interface_admin, label31, "label31");
  GLADE_HOOKUP_OBJECT (interface_admin, label32, "label32");
  GLADE_HOOKUP_OBJECT (interface_admin, label33, "label33");
  GLADE_HOOKUP_OBJECT (interface_admin, buttonMca, "buttonMca");
  GLADE_HOOKUP_OBJECT (interface_admin, buttonDeca, "buttonDeca");
  GLADE_HOOKUP_OBJECT (interface_admin, label29, "label29");
  GLADE_HOOKUP_OBJECT (interface_admin, label, "label");
  GLADE_HOOKUP_OBJECT (interface_admin, label23, "label23");
  GLADE_HOOKUP_OBJECT (interface_admin, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (interface_admin, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (interface_admin, buttonaa, "buttonaa");
  GLADE_HOOKUP_OBJECT (interface_admin, buttonma, "buttonma");
  GLADE_HOOKUP_OBJECT (interface_admin, buttonsa, "buttonsa");
  GLADE_HOOKUP_OBJECT (interface_admin, label24, "label24");

  return interface_admin;
}

GtkWidget*
create_interface_prop (void)
{
  GtkWidget *interface_prop;
  GtkWidget *fixed13;
  GtkWidget *notebook3;
  GtkWidget *fixed14;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkWidget *label40;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkWidget *label43;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *label46;
  GtkWidget *label47;
  GtkWidget *buttonMcp;
  GtkWidget *buttonDecp;
  GtkWidget *label35;
  GtkWidget *empty_notebook_page;
  GtkWidget *label36;
  GtkWidget *label37;

  interface_prop = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (interface_prop), _("window2"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (interface_prop), fixed13);

  notebook3 = gtk_notebook_new ();
  gtk_widget_show (notebook3);
  gtk_fixed_put (GTK_FIXED (fixed13), notebook3, 8, 16);
  gtk_widget_set_size_request (notebook3, 632, 368);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed14);

  label38 = gtk_label_new (_("Adresse mail"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed14), label38, 24, 128);
  gtk_widget_set_size_request (label38, 112, 40);

  label39 = gtk_label_new (_("Login"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed14), label39, 56, 96);
  gtk_widget_set_size_request (label39, 48, 24);

  label40 = gtk_label_new (_("Cin"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed14), label40, 40, 168);
  gtk_widget_set_size_request (label40, 80, 32);

  label41 = gtk_label_new (_("Num de t\303\251l\303\251phone"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed14), label41, 24, 208);
  gtk_widget_set_size_request (label41, 136, 32);

  label42 = gtk_label_new ("");
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed14), label42, 192, 136);
  gtk_widget_set_size_request (label42, 192, 24);

  label43 = gtk_label_new ("");
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed14), label43, 192, 168);
  gtk_widget_set_size_request (label43, 192, 24);

  label44 = gtk_label_new ("");
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed14), label44, 192, 208);
  gtk_widget_set_size_request (label44, 192, 24);

  label45 = gtk_label_new (_("Nom Complet"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed14), label45, 24, 48);
  gtk_widget_set_size_request (label45, 112, 32);

  label46 = gtk_label_new ("");
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed14), label46, 192, 96);
  gtk_widget_set_size_request (label46, 192, 24);

  label47 = gtk_label_new ("");
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed14), label47, 192, 48);
  gtk_widget_set_size_request (label47, 192, 24);

  buttonMcp = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (buttonMcp);
  gtk_fixed_put (GTK_FIXED (fixed14), buttonMcp, 496, 112);
  gtk_widget_set_size_request (buttonMcp, 104, 40);

  buttonDecp = gtk_button_new_with_mnemonic (_("Se D\303\251connecter"));
  gtk_widget_show (buttonDecp);
  gtk_fixed_put (GTK_FIXED (fixed14), buttonDecp, 472, 288);
  gtk_widget_set_size_request (buttonDecp, 130, 37);

  label35 = gtk_label_new (_("Compte"));
  gtk_widget_show (label35);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 0), label35);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook3), empty_notebook_page);

  label36 = gtk_label_new (_("Fidelit\303\251"));
  gtk_widget_show (label36);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 1), label36);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook3), empty_notebook_page);

  label37 = gtk_label_new (_("Reclamations"));
  gtk_widget_show (label37);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 2), label37);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (interface_prop, interface_prop, "interface_prop");
  GLADE_HOOKUP_OBJECT (interface_prop, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (interface_prop, notebook3, "notebook3");
  GLADE_HOOKUP_OBJECT (interface_prop, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (interface_prop, label38, "label38");
  GLADE_HOOKUP_OBJECT (interface_prop, label39, "label39");
  GLADE_HOOKUP_OBJECT (interface_prop, label40, "label40");
  GLADE_HOOKUP_OBJECT (interface_prop, label41, "label41");
  GLADE_HOOKUP_OBJECT (interface_prop, label42, "label42");
  GLADE_HOOKUP_OBJECT (interface_prop, label43, "label43");
  GLADE_HOOKUP_OBJECT (interface_prop, label44, "label44");
  GLADE_HOOKUP_OBJECT (interface_prop, label45, "label45");
  GLADE_HOOKUP_OBJECT (interface_prop, label46, "label46");
  GLADE_HOOKUP_OBJECT (interface_prop, label47, "label47");
  GLADE_HOOKUP_OBJECT (interface_prop, buttonMcp, "buttonMcp");
  GLADE_HOOKUP_OBJECT (interface_prop, buttonDecp, "buttonDecp");
  GLADE_HOOKUP_OBJECT (interface_prop, label35, "label35");
  GLADE_HOOKUP_OBJECT (interface_prop, label36, "label36");
  GLADE_HOOKUP_OBJECT (interface_prop, label37, "label37");

  return interface_prop;
}

GtkWidget*
create_interface_agent (void)
{
  GtkWidget *interface_agent;
  GtkWidget *fixed15;
  GtkWidget *notebook4;
  GtkWidget *fixed16;
  GtkWidget *fixed18;
  GtkWidget *label53;
  GtkWidget *label54;
  GtkWidget *label55;
  GtkWidget *label56;
  GtkWidget *label57;
  GtkWidget *label58;
  GtkWidget *label59;
  GtkWidget *label60;
  GtkWidget *label61;
  GtkWidget *label62;
  GtkWidget *buttonMcag;
  GtkWidget *buttonDecag;
  GtkWidget *label48;
  GtkWidget *fixed17;
  GtkWidget *treeview4;
  GtkWidget *buttonagac;
  GtkWidget *buttonagmc;
  GtkWidget *buttonagsc;
  GtkWidget *label49;
  GtkWidget *empty_notebook_page;
  GtkWidget *label50;
  GtkWidget *label51;
  GtkWidget *label52;

  interface_agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (interface_agent), _("window3"));

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (interface_agent), fixed15);

  notebook4 = gtk_notebook_new ();
  gtk_widget_show (notebook4);
  gtk_fixed_put (GTK_FIXED (fixed15), notebook4, 0, 24);
  gtk_widget_set_size_request (notebook4, 648, 432);

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (notebook4), fixed16);

  fixed18 = gtk_fixed_new ();
  gtk_widget_show (fixed18);
  gtk_fixed_put (GTK_FIXED (fixed16), fixed18, 0, 0);
  gtk_widget_set_size_request (fixed18, 0, 0);

  label53 = gtk_label_new (_("Adresse mail"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed18), label53, 24, 128);
  gtk_widget_set_size_request (label53, 112, 40);

  label54 = gtk_label_new (_("Login"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed18), label54, 56, 96);
  gtk_widget_set_size_request (label54, 48, 24);

  label55 = gtk_label_new (_("Cin"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed18), label55, 40, 168);
  gtk_widget_set_size_request (label55, 80, 32);

  label56 = gtk_label_new (_("Num de t\303\251l\303\251phone"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed18), label56, 24, 208);
  gtk_widget_set_size_request (label56, 136, 32);

  label57 = gtk_label_new ("");
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed18), label57, 192, 136);
  gtk_widget_set_size_request (label57, 192, 24);

  label58 = gtk_label_new ("");
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed18), label58, 192, 168);
  gtk_widget_set_size_request (label58, 192, 24);

  label59 = gtk_label_new ("");
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed18), label59, 192, 208);
  gtk_widget_set_size_request (label59, 192, 24);

  label60 = gtk_label_new (_("Nom Complet"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed18), label60, 24, 48);
  gtk_widget_set_size_request (label60, 112, 32);

  label61 = gtk_label_new ("");
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed18), label61, 192, 96);
  gtk_widget_set_size_request (label61, 192, 24);

  label62 = gtk_label_new ("");
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed18), label62, 192, 48);
  gtk_widget_set_size_request (label62, 192, 24);

  buttonMcag = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (buttonMcag);
  gtk_fixed_put (GTK_FIXED (fixed18), buttonMcag, 496, 112);
  gtk_widget_set_size_request (buttonMcag, 104, 40);

  buttonDecag = gtk_button_new_with_mnemonic (_("Se D\303\251connecter"));
  gtk_widget_show (buttonDecag);
  gtk_fixed_put (GTK_FIXED (fixed18), buttonDecag, 472, 288);
  gtk_widget_set_size_request (buttonDecag, 130, 37);

  label48 = gtk_label_new (_("Compte"));
  gtk_widget_show (label48);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 0), label48);

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (notebook4), fixed17);

  treeview4 = gtk_tree_view_new ();
  gtk_widget_show (treeview4);
  gtk_fixed_put (GTK_FIXED (fixed17), treeview4, 8, 32);
  gtk_widget_set_size_request (treeview4, 616, 296);

  buttonagac = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (buttonagac);
  gtk_fixed_put (GTK_FIXED (fixed17), buttonagac, 56, 352);
  gtk_widget_set_size_request (buttonagac, 88, 40);

  buttonagmc = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (buttonagmc);
  gtk_fixed_put (GTK_FIXED (fixed17), buttonagmc, 208, 352);
  gtk_widget_set_size_request (buttonagmc, 88, 40);

  buttonagsc = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (buttonagsc);
  gtk_fixed_put (GTK_FIXED (fixed17), buttonagsc, 360, 352);
  gtk_widget_set_size_request (buttonagsc, 88, 40);

  label49 = gtk_label_new (_("Liste Clients"));
  gtk_widget_show (label49);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 1), label49);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook4), empty_notebook_page);

  label50 = gtk_label_new (_("Catalogue"));
  gtk_widget_show (label50);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 2), label50);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook4), empty_notebook_page);

  label51 = gtk_label_new (_("Liste R\303\251servations"));
  gtk_widget_show (label51);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 3), label51);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook4), empty_notebook_page);

  label52 = gtk_label_new (_("Liste R\303\251clamations"));
  gtk_widget_show (label52);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 4), label52);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (interface_agent, interface_agent, "interface_agent");
  GLADE_HOOKUP_OBJECT (interface_agent, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (interface_agent, notebook4, "notebook4");
  GLADE_HOOKUP_OBJECT (interface_agent, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (interface_agent, fixed18, "fixed18");
  GLADE_HOOKUP_OBJECT (interface_agent, label53, "label53");
  GLADE_HOOKUP_OBJECT (interface_agent, label54, "label54");
  GLADE_HOOKUP_OBJECT (interface_agent, label55, "label55");
  GLADE_HOOKUP_OBJECT (interface_agent, label56, "label56");
  GLADE_HOOKUP_OBJECT (interface_agent, label57, "label57");
  GLADE_HOOKUP_OBJECT (interface_agent, label58, "label58");
  GLADE_HOOKUP_OBJECT (interface_agent, label59, "label59");
  GLADE_HOOKUP_OBJECT (interface_agent, label60, "label60");
  GLADE_HOOKUP_OBJECT (interface_agent, label61, "label61");
  GLADE_HOOKUP_OBJECT (interface_agent, label62, "label62");
  GLADE_HOOKUP_OBJECT (interface_agent, buttonMcag, "buttonMcag");
  GLADE_HOOKUP_OBJECT (interface_agent, buttonDecag, "buttonDecag");
  GLADE_HOOKUP_OBJECT (interface_agent, label48, "label48");
  GLADE_HOOKUP_OBJECT (interface_agent, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (interface_agent, treeview4, "treeview4");
  GLADE_HOOKUP_OBJECT (interface_agent, buttonagac, "buttonagac");
  GLADE_HOOKUP_OBJECT (interface_agent, buttonagmc, "buttonagmc");
  GLADE_HOOKUP_OBJECT (interface_agent, buttonagsc, "buttonagsc");
  GLADE_HOOKUP_OBJECT (interface_agent, label49, "label49");
  GLADE_HOOKUP_OBJECT (interface_agent, label50, "label50");
  GLADE_HOOKUP_OBJECT (interface_agent, label51, "label51");
  GLADE_HOOKUP_OBJECT (interface_agent, label52, "label52");

  return interface_agent;
}

