/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *interface1;
  GtkWidget *interface2;
  GtkWidget *interface3;
  GtkWidget *interface4;
  GtkWidget *interface5;
  GtkWidget *interface6;
  GtkWidget *interface7;
  GtkWidget *interface8;
  GtkWidget *interface9;
  GtkWidget *interface10;
  GtkWidget *interface11;
  GtkWidget *interface12;
  GtkWidget *interface13;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  interface1 = create_interface1 ();
  gtk_widget_show (interface1);
  interface2 = create_interface2 ();
  interface3 = create_interface3 ();
  interface4 = create_interface4 ();
  interface5 = create_interface5 ();
  interface6 = create_interface6 ();
  interface7 = create_interface7 ();
  interface8 = create_interface8 ();
  interface9 = create_interface9 ();
  interface10 = create_interface10 ();
  interface11 = create_interface11 ();
  interface12 = create_interface12 ();
  interface13 = create_interface13 ();

  gtk_main ();
  return 0;
}

